# Generated by Django 5.1.1 on 2024-09-09 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=100)),
                ('describe', models.TextField()),
                ('image', models.ImageField(upload_to='images/business')),
            ],
            options={
                'db_table': 'Business',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('delegate', models.CharField(max_length=255)),
                ('formation', models.DateField()),
                ('capital', models.BigIntegerField(default=0)),
                ('annual_revenue', models.BigIntegerField(default=0)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('fax', models.CharField(max_length=10)),
                ('employees_quantity', models.IntegerField(default=1)),
                ('business', models.TextField()),
                ('delivery_record', models.TextField()),
            ],
            options={
                'db_table': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='images/equipments')),
            ],
            options={
                'db_table': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('workplace', models.TextField()),
                ('working_hours', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('benefits', models.TextField()),
                ('holiday', models.TextField()),
            ],
            options={
                'db_table': 'Recruitment Requirement',
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_vacancy', models.CharField(max_length=100)),
                ('describe', models.TextField()),
                ('recruitment_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_vcc', to='Home.recruitmentrequirement')),
            ],
            options={
                'db_table': 'Job Vacancy',
            },
        ),
    ]
