# Generated by Django 5.1.1 on 2024-09-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
