# Generated by Django 5.1.1 on 2024-09-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_business_image_alter_equipment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'advise'), (1, 'recruitment'), (2, 'colab'), (3, 'other')], default=0)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('Furigana', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.IntegerField(choices=[(0, ''), (1, '愛知県'), (2, '秋田県'), (3, '青森県'), (4, '千葉県'), (5, '愛媛県'), (6, '福井県'), (7, '福岡県'), (8, '福島県'), (9, '岐阜県'), (10, '群馬県'), (11, '広島県'), (12, '北海道'), (13, '兵庫県'), (14, '茨城県'), (15, '石川県'), (16, '岩手県'), (17, '香川県'), (18, '鹿児島県\t'), (19, '神奈川県'), (20, '高知県'), (21, '熊本県'), (22, '京都府'), (23, '三重県'), (24, '宮城県'), (25, '宮崎県'), (26, '長野県'), (27, '長崎県'), (28, '奈良県'), (29, '新潟県'), (30, '大分県'), (31, '岡山県'), (32, '沖縄県'), (33, '大阪府'), (34, '佐賀県'), (35, '埼玉県'), (36, '滋賀県'), (37, '島根県'), (38, '静岡県'), (39, '栃木県'), (40, '徳島県'), (41, '東京都'), (42, '鳥取県'), (43, '富山県'), (44, '和歌山県'), (45, '山形県'), (46, '山口県'), (47, '山梨県')], default=0)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('fax', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(max_length=255)),
                ('request_detail', models.TextField()),
                ('is_apply', models.BooleanField(default=False)),
                ('contact_method', models.IntegerField(blank=True, choices=[(0, 'phone'), (1, 'email')], null=True)),
                ('contact_time', models.IntegerField(blank=True, choices=[(0, '9:00～12:00'), (1, '12:00～15:00'), (2, '15:00～18:00'), (3, '18:00～21:00')], null=True)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
