# Generated by Django 5.1.1 on 2024-09-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_contact_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_method',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'phone'), (2, 'email')], null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_time',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, '9:00～12:00'), (2, '12:00～15:00'), (3, '15:00～18:00'), (4, '18:00～21:00')], null=True),
        ),
    ]
