# Generated by Django 5.1.1 on 2024-09-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_contact_contact_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.IntegerField(choices=[(0, '製作の相談'), (1, '採用について'), (2, '協力企業について'), (3, 'その他')], default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_method',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, '電話'), (2, 'メール')], null=True),
        ),
    ]
