# Generated by Django 5.1.1 on 2024-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_contact_category_alter_contact_contact_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_method',
            field=models.CharField(blank=True, choices=[(None, ''), ('0', '電話'), ('1', 'メール')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_time',
            field=models.CharField(blank=True, choices=[(None, ''), ('0', '9:00～12:00'), ('1', '12:00～15:00'), ('2', '15:00～18:00'), ('3', '18:00～21:00')], max_length=1, null=True),
        ),
    ]
