# Generated by Django 5.1.1 on 2024-09-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_contact_contact_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_method',
            field=models.IntegerField(blank=True, choices=[(0, '両方'), (1, '電話'), (2, 'メール')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_time',
            field=models.IntegerField(blank=True, choices=[(0, 'いつでも'), (1, '9:00～12:00'), (2, '12:00～15:00'), (3, '15:00～18:00'), (4, '18:00～21:00')], max_length=1, null=True),
        ),
    ]
