# Generated by Django 5.1.1 on 2024-09-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_contact_contact_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Furigana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
