# Generated by Django 4.2.2 on 2024-10-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_contact_furigana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='fax',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
