# Generated by Django 4.2.2 on 2024-10-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_companyinfo_fax_alter_companyinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_method',
            field=models.IntegerField(blank=True, choices=[(0, '両方'), (1, '電話'), (2, 'メール')], null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_time',
            field=models.IntegerField(blank=True, choices=[(0, 'いつでも'), (1, '9:00～12:00'), (2, '12:00～15:00'), (3, '15:00～18:00'), (4, '18:00～21:00')], null=True),
        ),
    ]
