# Generated by Django 4.2.2 on 2024-10-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_contact_contact_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='annual_revenue',
            field=models.CharField(max_length=50),
        ),
    ]
