# Generated by Django 4.2.2 on 2024-10-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_companyinfo_annual_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='delegate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
