# Generated by Django 4.2.2 on 2024-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_companyinfo_delegate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='delivery_record',
            field=models.TextField(blank=True, null=True),
        ),
    ]
